CREATE TABLE IF NOT EXISTS teacher (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL
);

-- NOTE: If the class table becomes large, you may also want to add an index on
-- teacher_id
CREATE TABLE IF NOT EXISTS class (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id integer NOT NULL REFERENCES teacher (id),
  name text NOT NULL
);

CREATE TABLE IF NOT EXISTS student (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  age integer NOT NULL,
  grade integer NOT NULL
);

CREATE TABLE IF NOT EXISTS student_class (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id integer NOT NULL REFERENCES class (id),
  student_id integer NOT NULL REFERENCES student (id),
  -- Depending on how these scale you might also put these on a separate table
  attribute1 text NOT NULL,
  attribute2 text NOT NULL,
  attribute3 text NOT NULL
);

CREATE INDEX IF NOT EXISTS student_class_class_idx ON student_class (class_id);
