version: "3.7"
services:
  postgres:
    image: postgres:11.4-alpine
    container_name: postgres
    networks:
      - postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pickles
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
volumes:
  postgres-data:
networks:
  postgres:
    name: postgres
